image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python311-x64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install -r requirements_test.txt

build: off

test_script:
  - pytest --cov=blunderbuss --cov-report term-missing tests/

after_test:
  - pyinstaller --noconfirm --onefile --console -n blunderbuss --uac-admin app.py
  - cp -r data/ dist/
  - cp data/installer/*.dll dist/
  - cp README.* dist/
  - 7z a blunderbuss.zip dist/*
  - 7z rn blunderbuss.zip dist blunderbuss

artifacts:
  - path: blunderbuss.zip
    name: blunderbuss

deploy:
  - provider: GitHub
    tag: dev
    release: dev
    auth_token:
      secure: 32wi9EYebbPOK8c8u2acHuSm2Gs/Mhm9nhnUOKmkuh10ftCGcdGu3yTo2PRiuuN/
    artifact: blunderbuss.zip
    prerelease: true
    on:
      branch: main
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: 32wi9EYebbPOK8c8u2acHuSm2Gs/Mhm9nhnUOKmkuh10ftCGcdGu3yTo2PRiuuN/
    artifact: blunderbuss.zip
    prerelease: true
    on:
      APPVEYOR_REPO_TAG: true